const STORAGE_KEY="enosh_projects_v1";
const ADMIN_PASSWORD="enosh2026";
const defaultProjects=[
{id:1,color1:"#2B2E83",color2:"#17173A",tag:"Agroalimentaire",title:"Identité de marque",client:"Marque agroalimentaire locale",year:"2025",sector:"Agroalimentaire",desc:"Refonte complète de l'identité visuelle : logo, palette, typographies et déclinaisons sur l'ensemble des supports.",deliverables:["Logo & charte graphique","Palette & typographies","Déclinaisons print & digital"]},
{id:2,color1:"#F2941D",color2:"#FFB65C",tag:"Produit local",title:"Packaging",client:"Producteur local",year:"2025",sector:"Agroalimentaire",desc:"Conception d'un packaging pensé pour se démarquer en linéaire tout en restant fidèle à l'identité de la marque.",deliverables:["Design packaging","Fiches techniques impression","Déclinaisons formats"]},
{id:3,color1:"#3A3663",color2:"#1B1B3A",tag:"Calendrier",title:"Réseaux sociaux",client:"Marque grand public",year:"2024–2025",sector:"Communication",desc:"Mise en place d'un calendrier éditorial et de gabarits visuels réutilisables pour assurer une présence régulière et cohérente.",deliverables:["Calendrier éditorial","Gabarits de posts","Community management"]},
{id:4,color1:"#FFB65C",color2:"#F2941D",tag:"Print & digital",title:"Catalogue produits",client:"Gamme de produits agroalimentaires",year:"2024",sector:"Agroalimentaire",desc:"Réalisation d'un catalogue produits pensé pour la force commerciale : mise en page claire et déclinaison print/digitale.",deliverables:["Mise en page catalogue","Version print","Version digitale (PDF interactif)"]},
{id:5,color1:"#17173A",color2:"#2B2E83",tag:"Campagne",title:"Direction artistique",client:"Campagne de lancement",year:"2024",sector:"Communication",desc:"Direction artistique d'une campagne de lancement : univers visuel, choix des couleurs et coordination des supports.",deliverables:["Univers visuel de campagne","Coordination des supports","Suivi de production"]},
{id:6,color1:"#DB8110",color2:"#F2941D",tag:"PLV & fiches",title:"Supports commerciaux",client:"Force de vente terrain",year:"2024",sector:"Commercial",desc:"Conception de supports commerciaux et de PLV pensés pour le terrain.",deliverables:["PLV point de vente","Fiches produits","Outils d'aide à la vente"]}
];
function loadProjects(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY));return Array.isArray(p)?p:structuredClone(defaultProjects)}catch(e){return structuredClone(defaultProjects)}}
function saveProjects(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(projects));return true}catch(e){alert("Stockage local plein. Réduis la taille des images.");return false}}
let projects=loadProjects(), currentIndex=0, pendingImage=null, pendingRatio=null;
const $=id=>document.getElementById(id);
function esc(v=""){return String(v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function grad(p){return `linear-gradient(135deg,${p.color1||"#2B2E83"},${p.color2||"#17173A"})`}
function renderGrid(filter="Tous"){
 const list=filter==="Tous"?projects:projects.filter(p=>((p.tag||"")+" "+(p.title||"")+" "+(p.sector||"")).toLowerCase().includes(filter.toLowerCase()));
 $("workGrid").innerHTML=list.map(p=>`<button class="work-card" data-id="${p.id}"><div class="work-img" style="background:${grad(p)}">${p.image?`<img src="${p.image}" alt="${esc(p.title)}" loading="lazy">`:""}</div><div class="work-card-content"><span class="work-tag">${esc(p.tag)}</span><h3>${esc(p.title)} <span class="work-arrow">↗</span></h3></div></button>`).join("");
 document.querySelectorAll(".work-card").forEach(c=>c.addEventListener("click",()=>openModal(Number(c.dataset.id))));
}
function openModal(id){currentIndex=projects.findIndex(p=>p.id===id);if(currentIndex<0)return;const p=projects[currentIndex];$("modalTag").textContent=p.tag||"";$("modalTitle").textContent=p.title||"";$("modalMeta").textContent=[p.client,p.year,p.sector].filter(Boolean).join(" · ");$("modalDesc").textContent=p.desc||"";$("modalDeliverables").innerHTML=(p.deliverables||[]).map(x=>`<li>${esc(x)}</li>`).join("");const hero=$("modalHero");hero.style.background=p.image?`url("${p.image}") center/cover no-repeat`:grad(p);$("modalOverlay").classList.add("open");$("modalOverlay").setAttribute("aria-hidden","false")}
function closeModal(){$("modalOverlay").classList.remove("open");$("modalOverlay").setAttribute("aria-hidden","true")}
function moveModal(step){if(!projects.length)return;currentIndex=(currentIndex+step+projects.length)%projects.length;openModal(projects[currentIndex].id)}
$("modalClose").addEventListener("click",closeModal);$("modalOverlay").addEventListener("click",e=>{if(e.target===$("modalOverlay"))closeModal()});$("modalPrev").addEventListener("click",()=>moveModal(-1));$("modalNext").addEventListener("click",()=>moveModal(1));
document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeModal();closeAdmin()}if($("modalOverlay").classList.contains("open")&&e.key==="ArrowRight")moveModal(1);if($("modalOverlay").classList.contains("open")&&e.key==="ArrowLeft")moveModal(-1)});
document.querySelectorAll(".filters button").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".filters button").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderGrid(b.dataset.filter)}));
$("contactForm").addEventListener("submit",e=>{e.preventDefault();$("contactForm").querySelector(".field-status").textContent="Merci ! Pour l'instant, ce formulaire est une démonstration. Utilise l'adresse email ci-dessus pour envoyer réellement ton message.";});
let adminAuthed=false;
function openAdmin(){$("adminOverlay").classList.add("open");$("adminOverlay").setAttribute("aria-hidden","false");if(adminAuthed)showAdminArea()}
function closeAdmin(){$("adminOverlay").classList.remove("open");$("adminOverlay").setAttribute("aria-hidden","true")}
$("adminOpen").addEventListener("click",openAdmin);$("adminClose").addEventListener("click",closeAdmin);$("adminLoginBtn").addEventListener("click",()=>{if($("adminPassword").value===ADMIN_PASSWORD){adminAuthed=true;$("adminLoginStatus").textContent="Connecté.";showAdminArea()}else $("adminLoginStatus").textContent="Mot de passe incorrect."});
function showAdminArea(){$("adminLogin").hidden=true;$("adminArea").hidden=false;renderAdminList();resetForm()}
function renderAdminList(){$("adminList").innerHTML=projects.map(p=>`<div class="admin-item"><div><div class="admin-item-title">${esc(p.title)}</div><small>${esc(p.tag)} · ${esc(p.year||"")}</small></div><div class="admin-item-actions"><button data-edit="${p.id}">Modifier</button><button data-delete="${p.id}">Supprimer</button></div></div>`).join("")+`<button id="newProject" class="btn btn-primary" style="margin-top:18px">+ Nouveau projet</button>`;document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>editProject(Number(b.dataset.edit)));document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>deleteProject(Number(b.dataset.delete)));$("newProject").onclick=resetForm}
function resetForm(){ $("adminForm").reset();$("projectId").value="";pendingImage=null;pendingRatio=null;$("imagePreview").style.background="";$("adminStatus").textContent=""}
function editProject(id){const p=projects.find(x=>x.id===id);if(!p)return;$("projectId").value=p.id;$("pTitle").value=p.title||"";$("pTag").value=p.tag||"";$("pClient").value=p.client||"";$("pYear").value=p.year||"";$("pSector").value=p.sector||"";$("pColor1").value=p.color1||"#2B2E83";$("pColor2").value=p.color2||"#17173A";$("pDesc").value=p.desc||"";$("pDeliverables").value=(p.deliverables||[]).join("\n");pendingImage=p.image||null;pendingRatio=p.imageRatio||null;$("imagePreview").style.background=p.image?`url("${p.image}") center/cover no-repeat`:grad(p);window.scrollTo({top:document.body.scrollHeight,behavior:"smooth"})}
function deleteProject(id){if(!confirm("Supprimer ce projet ?"))return;projects=projects.filter(p=>p.id!==id);saveProjects();renderAdminList();renderGrid()}
$("pImage").addEventListener("change",e=>{const f=e.target.files[0];if(!f)return;if(!f.type.startsWith("image/")||f.size>3*1024*1024){alert("Image invalide ou supérieure à 3 Mo.");e.target.value="";return}const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{pendingRatio=img.naturalWidth/img.naturalHeight};img.src=r.result;pendingImage=r.result;$("imagePreview").style.background=`url("${r.result}") center/cover no-repeat`};r.readAsDataURL(f)});
$("removeImage").addEventListener("click",()=>{pendingImage=null;pendingRatio=null;$("pImage").value="";$("imagePreview").style.background=""});
$("adminCancel").addEventListener("click",resetForm);
$("adminForm").addEventListener("submit",e=>{e.preventDefault();const id=$("projectId").value?Number($("projectId").value):Date.now();const p={id,title:$("pTitle").value.trim(),tag:$("pTag").value.trim(),client:$("pClient").value.trim(),year:$("pYear").value.trim(),sector:$("pSector").value.trim(),color1:$("pColor1").value||"#2B2E83",color2:$("pColor2").value||"#17173A",desc:$("pDesc").value.trim(),deliverables:$("pDeliverables").value.split("\n").map(x=>x.trim()).filter(Boolean),image:pendingImage,imageRatio:pendingRatio};const i=projects.findIndex(x=>x.id===id);if(i>=0)projects[i]=p;else projects.push(p);if(saveProjects()){$("adminStatus").textContent="Projet enregistré.";renderAdminList();renderGrid()}});
$("adminExport").addEventListener("click",()=>{const blob=new Blob([JSON.stringify(projects,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="enosh-projects.json";a.click();URL.revokeObjectURL(a.href)});
$("adminImport").addEventListener("change",e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);if(!Array.isArray(data))throw Error();projects=data;saveProjects();renderAdminList();renderGrid();$("adminStatus").textContent="Import réussi."}catch(err){$("adminStatus").textContent="Fichier JSON invalide."}};r.readAsText(f)});
$("adminReset").addEventListener("click",()=>{if(confirm("Réinitialiser tous les projets aux valeurs par défaut ?")){projects=structuredClone(defaultProjects);saveProjects();renderAdminList();renderGrid();$("adminStatus").textContent="Projets réinitialisés."}});
renderGrid();